site_name: Citrix XenCenter Plugin Specification
site_description: Citrix XenCenter Plugin Specification
site_title: Developer Documentation

copyright: 'Copyright &copy; 1999-2019 Citrix Systems, Inc. All rights reserved. '

extra_css:
  - 'assets/stylesheets/extra.css'

theme:
  name: null
  custom_dir: devdocs-theme
  include_search_page: false
  search_index_only: true
  language: en
  feature:
    tabs: false
  palette:
    primary: white
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  favicon: /media/favicon.ico
  logo: https://developer-docs.citrix.com/_static/Citrix_Logo_Black.png

extra:
  social:
    - type: youtube
      link: https://www.youtube.com/channel/UCiOupk9QF6jdk3EDKTHDykA
    - type: github-alt
      link: https://github.com/citrix
    - type: twitter
      link: https://twitter.com/citrixdeveloper
    - type: linkedin
      link: https://www.linkedin.com/company/citrix/
  search:
    language: 'en'
    tokenizer: '[\s\-\.]+'

plugins: 
  - search
   
markdown_extensions:
  - admonition
  - codehilite
  - toc
  - footnotes
  - meta

nav:
- Introduction: index.md
- XML Configuration File: xml-configuration.md
- Features: features.md
- Commands: commands.md
- Resources and Internationalization: resources-and-internationalization.md
- Deploying: deploying.md
